function spec = defaultSpec()
%DEFAULTSPEC Default replay sequence.

move = struct( ...
    "type", "square", ...
    "durationSeconds", 1.0, ...
    "amplitude", 0.4 * 40000, ...
    "periodSeconds", 1.0);

menuetto = struct( ...
    "type", "wav", ...
    "file", "menuetto_1.wav", ...
    "clip", 0.1, ...
    "scale", 3 * 40000, ...
    "trimTailSeconds", 0, ...
    "motionAmplitude", 4000, ...
    "motionFrequencyHz", 2.0);

mario = struct( ...
    "type", "wav", ...
    "file", "mario.wav", ...
    "clip", 0.1, ...
    "scale", 3 * 40000, ...
    "trimTailSeconds", 17, ...
    "motionAmplitude", 4000, ...
    "motionFrequencyHz", 2.0);

spec = struct();
spec.name = "default";
spec.items = {move, menuetto, move, mario};
end
