function symbols = diskSymbols(namespace)
%DISKSYMBOLS PLC symbols used by the Disk_B controller.

if nargin < 1 || strlength(strtrim(string(namespace))) == 0
    namespace = "Disk_B";
end

prefix = string(namespace) + ".";
symbols = struct( ...
    "controlword", prefix + "Controlword", ...
    "targetTorque", prefix + "TargetTorque", ...
    "commutationAngle", prefix + "CommutationAngle", ...
    "statusword", prefix + "Statusword", ...
    "torqueActual", prefix + "TorqueActual", ...
    "runCmd", prefix + "RunCmd", ...
    "torqueCmd", prefix + "TorqueCmd", ...
    "torqueTarget", prefix + "TorqueTarget", ...
    "torqueRampStep", prefix + "TorqueRampStep", ...
    "angle", prefix + "Angle", ...
    "angleIncTarget", prefix + "AngleIncTarget", ...
    "angleIncActual", prefix + "AngleIncActual", ...
    "angleIncRampStep", prefix + "AngleIncRampStep", ...
    "angleIncDemand", prefix + "AngleIncDemand", ...
    "torqueDemand", prefix + "TorqueDemand", ...
    "swMasked", prefix + "swMasked");
end
