function types = netTypes()
%NETTYPES .NET scalar names used with TwinCAT ADS WriteAny/ReadAny.

types = struct( ...
    "bool", "System.Boolean", ...
    "i16", "System.Int16", ...
    "u16", "System.UInt16", ...
    "u32", "System.UInt32", ...
    "f64", "System.Double");
end
