function symbols = symbols(namespace)
%SYMBOLS PLC symbols used by the audio replay controller.

if nargin < 1 || strlength(strtrim(string(namespace))) == 0
    namespace = "Audio_A";
end

prefix = string(namespace) + ".";
symbols = struct( ...
    "controlword", prefix + "Controlword", ...
    "controlwords", [prefix + "Controlword", prefix + "Controlword2", prefix + "Controlword3"], ...
    "statusword", prefix + "Statusword", ...
    "statuswords", [prefix + "Statusword", prefix + "Statusword2", prefix + "Statusword3"], ...
    "commandTable", prefix + "commandTable", ...
    "commandTables", [prefix + "commandTable", prefix + "commandTable2", prefix + "commandTable3"], ...
    "tableLen", prefix + "tableLen", ...
    "repeatCount", prefix + "repeatCount", ...
    "runReq", prefix + "runReq", ...
    "resetReq", prefix + "resetReq", ...
    "estopReq", prefix + "estopReq", ...
    "idx", prefix + "idx", ...
    "cycleCount", prefix + "cycleCount", ...
    "playbackDone", prefix + "playbackDone", ...
    "errorCode", prefix + "errorCode", ...
    "outputValue", prefix + "outputValue", ...
    "outputValues", [prefix + "outputValue", prefix + "outputValue2", prefix + "outputValue3"], ...
    "state", prefix + "state");
end
